### ISSUE TITLE
Can't lunch the app

### ISSUE THREAD

**Issue by moncefbettaieb** [saurzcode/twitter-stream#1]
After a build succes with maven , i run this commande to execute the jar : 
java -cp target/twitter-stream-0.0.1-SNAPSHOT.jar com.saurzcode.twitter.TwitterKafkaProducer 
but i have this issue : 
Exception in thread "main" java.lang.NoClassDefFoundError: com/twitter/hbc/core/endpoint/StreamingEndpoint

**Comment by ledurnan** [comment]
I'm having the same issue. Did you manage to resolve?

**Comment by Nibras1920** [comment]
I transformed the repository to an eclipse project with maven eclipse:eclipse then I built the project with eclispe.
I solved the issue with this solution.

**Comment by moncefbettaieb** [comment]
I transformed the repository to an eclipse project with maven eclipse:eclipse then I built the project with eclispe.
I solved the issue with this solution.

**Comment by ledurnan** [comment]
Thanks. I solved it by running from maven with exec:java.

**Comment by SyedJameer** [comment]
Getting Error like the can anyone upload the updated pom.xml 

[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by anshuGithubData** [comment]
Hello @ledurnan 
I am also facing the same issue while submitting the job using - 
java -cp target/twitter-stream-0.0.1-SNAPSHOT.jar com.saurzcode.twitter.TwitterKafkaProducer
I am using maven too to build it. Would you explain bit more on how you are doing it with "exec:java" [Well, I am quite new in this!]
Thanks

**Comment by anshuGithubData** [comment]
Hello @ledurnan again!
I was able to execute it by using the following comman
mvn exec:java -Dexec.mainClass="com.saurzcode.twitter.TwitterKafkaProducer" -Dexec.args="1 2 3 4"
Thanks!
